/* Generated by the Dustbin::Games LuaBind Python Script (w) 2020 by Christian Keimel / Dustbin::Games */
#pragma once

#include <_generated/lua/lua_tables.h>
#include <luawrap.hpp>
#include <LUA/ILuaClass.h>
#include <irrlicht/irrlicht.h>

/**
 * @class CCLuaCameraObject
 * @author Dustbin::Games LuaBind Python Script
 * A LUA camera object for controlling a 3d camera from LUA
 */
class CLuaCameraObject : public ILuaClass {
  protected:
    irr::scene::ICameraSceneNode * m_camera;  /**< The Irrlicht camera instance */

    void *getObjectFromLuaStack(const std::string &a_sIdentifier);

  public:
    CLuaCameraObject();
    virtual ~CLuaCameraObject();

    /**
     * Adds a new camera to the scene
     */
    void initialize();
    /**
     * Set the position of the camera
     * @param The new camera position
     */
    void setposition(const SVector3d &a_position);
    /**
     * Make this camera the scene manager's active camera
     */
    void activate();
    /**
     * Set the target of the camera
     * @param The new camera target
     */
    void settarget(const SVector3d &a_target);
    /**
     * Set the up-vector of the camera
     * @param The new camera up-vector
     */
    void setupvector(const SVector3d &a_upvector);

    static void registerMethods(lua_State *a_pState);
};
