/* Generated by the Dustbin::Games LuaBind Python Script (w) 2020 by Christian Keimel / Dustbin::Games */
#pragma once

#include <luawrap.hpp>
#include <lua/ILuaClass.h>
#include <irrlicht/irrlicht.h>
#include <_generated/lua/CLuaSingleton_dialog.h>

/**
 * @class CCLuaScript_dialog
 * @author Dustbin::Games LuaBind Python Script
 * LUA script to handle 3d dialog
 */
class CLuaScript_dialog : public ILuaClass {
  protected:

    CLuaSingleton_dialog *m_LuaSgt_dialog;

    void *getObjectFromLuaStack(const std::string &a_sIdentifier);

  public:
    CLuaScript_dialog(const std::string &a_sScript);
    virtual ~CLuaScript_dialog();

    /**
     * This function is called when the script starts, should be used for initialization and such
     */
    void initialize();
};
