/* Generated by the Dustbin::Games LuaBind Python Script (w) 2020 by Christian Keimel / Dustbin::Games */
#pragma once

#include <luawrap.hpp>
#include <LUA/ILuaClass.h>
#include <irrlicht/irrlicht.h>

/**
 * @class CCLuaSingleton_dialog
 * @author Dustbin::Games LuaBind Python Script
 * Singleton to handle a 3d dialog
 */
class CLuaSingleton_dialog : public ILuaClass {
  protected:

    void *getObjectFromLuaStack(const std::string &a_sIdentifier);

  public:
    CLuaSingleton_dialog(lua_State *a_State);
    virtual ~CLuaSingleton_dialog();

    /**
     * Load an Irrlicht scene file
     * @param Name of the 3d Irrlicht scene
     */
    void loadscene(const std::string &a_filename);
};
