#pragma once

/** This file was generated by the Dustbin::Games LUAWrapGenerator (w) 2020 by Christian Keimel **/

#include <luawrap.hpp>
#include <string>
#include <vector>
#include <map>

// 3d vector
struct SVector3d {
  float m_x;
  float m_y;
  float m_z;

  SVector3d();

  void pushToStack(lua_State *a_pState) const;
  void loadFromStack(lua_State *a_pState);
  void copyFrom(const SVector3d &a_cOther);
};

// RGBA color information
struct SColor {
  int m_r;
  int m_g;
  int m_b;
  int m_a;

  SColor();

  void pushToStack(lua_State *a_pState) const;
  void loadFromStack(lua_State *a_pState);
  void copyFrom(const SColor &a_cOther);
};

